- name: Install Nginx 
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Start Nginx & Enable
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Run Common-Tasks
  ansible.builtin.import_role:
    name: common 
    tasks_from: delete-download-code

# if there is change in configuration only, then you need to restart nginx
- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx

# - name: Restart Nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted